# action.yml
name: 'Build custom Jenkins job'
description: 'Trigger jenkins job'
inputs:
  jenkins-url:
    description: 'jenkins server url'
    required: true
  jenkins-token:
    description: 'token to access jenkins server'
    required: true
  user:
    description: "user name"
    required: true
  job-path:
    description: 'job/folder_name/job/job_name'
    required: true
  jenkins-port:
    description: "Jenkins server port"
    required: true
  job-params:
    description: "params to run the job. JSON string. i.e '{'param1': 'value1', 'param2': 'value2'}' "
    required: false
  is-secure:
    description: "Is this server accessed on HTTPS?"
    required: false
outputs:
  job_status:
    description: 'Build status'
runs:
  # using: 'docker'
  # image: 'docker://270171913989.dkr.ecr.us-west-2.amazonaws.com/hostaway:python-3.8'
  # args:
  #   - ${{ inputs.jenkins-url }}
  #   - ${{ inputs.jenkins-token }}
  #   - ${{ inputs.user }}
  #   - ${{ inputs.job-path }}
  #   - ${{ inputs.jenkins-port }}
  #   - ${{ inputs.job-params }}
  #   - ${{ inputs.is-secure }}
  using: "composite"
  steps:
    - name: Login to ECR
      shell: bash
      run: |
        aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 270171913989.dkr.ecr.us-west-2.amazonaws.com

    - name: Run Jenkins job in ECR image
      shell: bash
      run: |
        docker run --rm \
          -e JENKINS_URL="${{ inputs.jenkins-url }}" \
          -e JENKINS_TOKEN="${{ inputs.jenkins-token }}" \
          -e USER="${{ inputs.user }}" \
          -e JOB_PATH="${{ inputs.job-path }}" \
          -e JENKINS_PORT="${{ inputs.jenkins-port }}" \
          -e JOB_PARAMS="${{ inputs.job-params }}" \
          -e IS_SECURE="${{ inputs.is-secure }}" \
          270171913989.dkr.ecr.us-west-2.amazonaws.com/hostaway:python-3.8
branding:
  icon: 'arrow-right-circle'
  color: 'blue'
